name: Ozan Oke
favicon: null
layout_spectrum: 0.6553740182425827
typography_spectrum: 0.6135874295141548
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.24748501926660538
  lightness: 0.41515732556581497
  saturation: 0.029570034705102444
  rhythmicContrast: 0.1975686913356185
purpose: []
